version: '3'
services:
  backend:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
